# Generated by Django 4.2.11 on 2024-05-09 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id'], 'verbose_name': '뉴스', 'verbose_name_plural': '뉴스모음'},
        ),
    ]
